swagger: '2.0'
info:
  version: '1.0.0'
  title: Atacadista
  description: API disponibilizada pelo Atacadista
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /pedido:
    post:
      summary: "Cria-se uma solicitação de pedido. Esta solicitação é armazenada e pendente de confirmação."
      parameters:
        - name: solicitação de pedido
          description: "É passado uma lista de solicitações. Em que cada uma contem o cod do produto, a quantidade e uma observação (opcional)"
          in: body
          required: true
          schema:
            type: array
            items:
              $ref: "#/definitions/SolicitacaoDTO"
      responses: 
        '200':
          description: 'ok.'
          schema:
            $ref: "#/definitions/PedidoDTO"
  /pedido/{id}:
    parameters:
      - name: id
        in: path
        required: true
        type: integer
        description: "Chave do pedido. Campo número do objeto PedidoDTO"
    get:
      summary: "Operação que recupera o objeto Pedido: seu status e data de entrega"
      responses:
        '200':
          description: 'ok.'
          schema:
            $ref: "#/definitions/PedidoDTO"
    put:
      summary: "Operação que aceita o pedido e formaliza o pedido. O status passa de aguardando confirmação para solicitado"
      responses:
        '200':
          description: 'ok.'
          schema:
            $ref: "#/definitions/PedidoDTO"
    delete:
      summary: "Operação que rejeita o pedido. Status do pedido passa para cancelado"
      responses:
        '200':
          description: 'ok. Pedido rejeitado com sucesso.'
  /pedido/{id}/produtos:
    get:
      summary: "Retorna os produtos referente a determinado pedido"
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          description: "Número referente ao pedido."
      responses:
        '200':
          description: 'ok.'
          schema:
            type: array
            items:
              $ref: "#/definitions/PedidoDTO"
definitions:
  SolicitacaoDTO:
    type: object
    properties:
      codProduto:
        type: integer
      quantidade:
        type: integer
      observacao: 
        description: "Campo opcional para o caso do cliente desejar colocar alguma observação sobre o produto requerido"
        type: string 
  PedidoDTO:
    type: object
    properties:
      numero:
        description: "Número identificador do pedido"
        type: integer
      dataEntrega:
        description: "Data de entrega estimada caso o pedido seja aceito"
        type: string
        format: date
      status:
        type: string
        enum: [Aguardando Confirmação, Solicitado, Em fabricação, Finalizado, Despachado, Cancelado]